# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81f1b60b575286b5c8ae36ce719c7e07ddd693b371da6024bdf1269686c80a844ceda219bc19016d1370ec19ef5e22fb825f246b3c4f0170a943af3691cd6c9

test:
  secret_key_base: 7642101a9cb3a297bee77e6f44211f34577c62cb6d14bb2bf0080d0bfff21426a8e58301b546a400b591e627ba33db4802e0e34e43c21f54bf6f1d9eb0102e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
